services:
  frontend:
    build:
      context: .
      dockerfile: Streamlit_Frontend/Dockerfile
    image: frontend:latest
    ports:
      - 8501:8501
    networks:
      - project_network
    depends_on:
      - backend
    volumes:
      - ./Streamlit_Frontend:/app/frontend

  backend:
    build:
      context: .
      dockerfile: FastAPI_Backend/Dockerfile
    image: backend:latest
    ports:
      - 8080:7860
    networks:
      - project_network
    volumes:
      - ./FastAPI_Backend:/app/backend
      - ./Data:/app/Data

networks:
  project_network: